#!/bin/sh
set -e
# Automatically added by dh_installemacsen/14.5
if { [ "$1" = "install" ] || [ "$1" = "upgrade" ]; } \
	&& [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --preinst uim-el
fi
# End automatically added section
