#!/bin/sh
set -e
# Automatically added by dh_installemacsen/14.5
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common ] && [ -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm uim-el
fi
# End automatically added section
