#!/bin/sh
set -e

if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
	update-alternatives --remove uim-toolbar \
		/usr/bin/uim-toolbar-gtk3-systray 
	update-alternatives --remove uim-toolbar \
		/usr/bin/uim-toolbar-gtk3
fi



exit 0
