#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
	update-alternatives --remove uim-toolbar \
		/bin/true
        ;;
    upgrade|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installdeb/14.5
dpkg-maintscript-helper mv_conffile /etc/uim/installed-modules.scm /var/lib/uim/installed-modules.scm 1:1.8.1-3\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/uim/loader.scm /var/lib/uim/loader.scm 1:1.8.1-3\~ -- "$@"
# End automatically added section


exit 0
